const UserRouter = require("./UserRouter");
const productsRouter = require("./products.route");
const ShipperRouter = require("./shipperRouter");
const orderRouter = require("./orderRouter");
const customerRouter = require("./customerRouter");
const supplierRouter = require("./supplierRouter");
const importReceiptRoutes = require("./importReceiptRoute");
const importDetailRoutes = require("./importDetailRoutes");
const exportReceiptRoutes = require("./exportReceiptRoutes");
const exportDetailRoutes = require("./exportDetailRoutes");
const inventoryRouter = require("./inventoryRouter");
const stockRouter = require("./stockRouter");
const statisticsRouter = require("./statisticsRouter");
const notificationRouter = require("./notificationRouter");
const twoFactorRouter = require("./twoFactorRouter");
const pinRouter = require("./pinRouter");
const backupRouter = require("./backupRouter");
const inventoryCountRouter = require("./inventoryCountRouter");
const locationRouter = require("./locationRouter");

const routes = (app) => {
  app.use("/api/v1/user", UserRouter);
  app.use("/api/v1/products", productsRouter);
  app.use("/api/v1/shipper", ShipperRouter);
  app.use("/api/v1/orders", orderRouter);
  app.use("/api/v1/customer", customerRouter);
  app.use("/api/v1/suppliers", supplierRouter);
  app.use("/api/v1/import-receipt", importReceiptRoutes);
  app.use("/api/v1/import-detail", importDetailRoutes);
  app.use("/api/v1/export-receipt", exportReceiptRoutes);
  app.use("/api/v1/export-detail", exportDetailRoutes);
  app.use("/api/v1/inventory", inventoryRouter);
  app.use("/api/v1/stock", stockRouter);
  app.use("/api/v1/statistics", statisticsRouter);
  app.use("/api/v1/notifications", notificationRouter);
  app.use("/api/v1/2fa", twoFactorRouter);
  app.use("/api/v1/pin", pinRouter);
  app.use("/api/v1/backup", backupRouter);
  app.use("/api/v1/inventory-count", inventoryCountRouter);
  app.use("/api/v1/locations", locationRouter);
};
module.exports = routes;
